#!/usr/bin/perl

# Consistency checking script for wikimap files
# By John Mark Ockerbloom, University of Pennsylvania (everybodyslibraries.com)
# Version as of 12 May 2017
#
# This code is made available, "as-is" and unsupported, under the
# Educational Community License 2.0 (http://opensource.org/licenses/ecl2.php)


my %lctowiki;
my %wikitolc;


my $unassignedcount = 0;

sub checkmapfile {
  my ($wikimap) = @_;

  open IN, "< $wikimap" or die "can't open $wikimap";
  while (my $line = <IN>) {
    next if ($line =~ /^#/);
    chop $line;
    if ($line =~ /(.*)\|(.*)\|(.*)/) {
      my ($lc, $sign, $wiki) = ($1, $2, $3);
      if ($lc =~ /^\s/ || $lc =~ /\s$/ || $wiki =~ /^\s/ || $wiki =~ /\s$/) {
        print STDERR "Extra spaces: $line\n";
      }
      if ($lc =~ /\|/) {
        print STDERR "Too many separators: $line\n";
      }
      if ($lc =~ /[^\x00-\x7f]/) {
        print STDERR "Non-ASCII: $line\n";
      }
      if ($sign eq "" || $sign eq "->" || $sign eq '=' || $sign eq "<->") {
        $unassignedcount++ if (!$sign);
        if ($lctowiki{$lc}) {
          print STDERR "$line: $lc already -> $lctowiki{$lc}\n";
        } else {
          $lctowiki{$lc} = $wiki;
        }
      }
      if ($sign eq "<-" || $sign eq "<->" || $sign eq "=") {
        if ($wikitolc{$wiki}) {
          print STDERR "$line: $wikitolc{$wiki} already <-  $wiki\n";
        } else {
          $wikitolc{$wiki} = $lc;
        }
      }
      if ($sign ne "" && $sign ne "->" && $sign ne '=' && $sign ne "<->"
          && $sign ne "<-") {
        print STDERR "$line: sign not recognized\n";
      }
    } else {
       print STDERR "Badly formed line: $line\n";
    }
  }
  close IN;
}

if (scalar(@ARGV)) {
  foreach $arg(@ARGV) {
    checkmapfile ($arg);
  }
} else {
  checkmapfile ("wikimap");
  checkmapfile ("wikiworksmap");
}

if ($unassignedcount) {
  print "$unassignedcount lines not yet signed\n";
}
