#!/usr/bin/perl

# Consistency checking script for a wikimap file
# By John Mark Ockerbloom, University of Pennsylvania (everybodyslibraries.com)
# Version as of 24 May 2013
#
# This code is made available, "as-is" and unsupported, under the
# Educational Community License 2.0 (http://opensource.org/licenses/ecl2.php)


my %lctowiki;
my %wikitolc;

my $wikimap = "wikimap";

my $unassignedcount = 0;

open IN, "< $wikimap" or die "can't open $wikimap";
while (my $line = <IN>) {
  next if ($line =~ /^#/);
  chop $line;
  if ($line =~ /(.*)\|(.*)\|(.*)/) {
    my ($lc, $sign, $wiki) = ($1, $2, $3);
    if ($sign eq "" || $sign eq "->" || $sign eq '=' || $sign eq "<->") {
      $unassignedcount++ if (!$sign);
      if ($lcwowiki{$lc}) {
        print STDERR "$line: $lc already -> $lctowiki{$lc}\n";
      } else {
        $lcwowiki{$lc} = $wiki;
      }
    }
    if ($sign eq "<-" || $sign eq "<->" || $sign eq "=") {
      if ($wikitolc{$wiki}) {
        print STDERR "$line: $wikitolc{$wiki} already <-  $wiki\n";
      } else {
        $wikitolc{$wiki} = $lc;
      }
    }
    if ($sign ne "" && $sign ne "->" && $sign ne '=' && $sign ne "<->"
        && $sign ne "<-") {
      print STDERR "$line: sign not recognized\n";
    }
  } else {
     print STDERR "Badly formed line: $line\n";
  }
}

close IN;

if ($unassignedcount) {
  print "$unassignedcount lines not yet signed\n";
}
